### ISSUE TITLE
userReview populating private fields on user content type for logged in user

### ISSUE THREAD

**Issue by Previesam** [luisguve/strapi-plugin-ratings#4]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi-plugin-ratings@1.1.8` for the project I'm working on.

userReview field was not properly sanitizing user data thereby returning the hashed password and other private fields in the request when the user is logged in.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/strapi-plugin-ratings/server/controllers/reviews.js b/node_modules/strapi-plugin-ratings/server/controllers/reviews.js
index 2b3b7f3..3400c2f 100644
--- a/node_modules/strapi-plugin-ratings/server/controllers/reviews.js
+++ b/node_modules/strapi-plugin-ratings/server/controllers/reviews.js
@@ -38,6 +38,19 @@ module.exports = {
         averageScore = score.average
       }
     }
+
+    const sanitizeOutput = (user, pub) => {
+      const {
+        password,
+        resetPasswordToken,
+        confirmationToken,
+        ...sanitizedUser
+      } = user; // be careful, you need to omit other private attributes yourself
+      const { email, role, phone_number, addresses, ...publicUser } =
+        sanitizedUser;
+      return pub ? publicUser : sanitizedUser;
+    };
+
     // Check whether the user has already posted a review
     if (user) {
       userReview = await strapi.db.query("plugin::ratings.review").findOne({
@@ -54,6 +67,8 @@ module.exports = {
         // Exclude user review
         reviews = reviews.filter(r => r.id !== userReview.id)
       }
+
+      userReview = { ...userReview, author: sanitizeOutput(userReview.author, "public") }
     }
     ctx.body = {
       reviewsCount,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by luisguve** [comment]
Hi there,

Thank you for opening this issue. You are right, that data should not be sent along with the review.

So the problem was that `strapi.db.query` uses `select` syntax instead of `fields` to populate fields in relations, and the API controller was using `fields` syntax inside a `strapi.db.query`.

I just fixed it in [version 1.1.9](https://github.com/luisguve/strapi-plugin-ratings/commit/5b9c91ff8c9efc6e62d1be892814572f6f610861).

By the way, there is a helper function called `sanitize`, which is included in the package `@strapi/utils` and it's job is to remove sensitive fields from the data before sending it in the response.
